ENH: Replace --no-merges with --first-parent for comment
InsightSoftwareConsortium/ITKPerformanceBenchmarking pull request #76
Opened 2019-03-16 17:56 UTC by hjmjohnson

When walking through the git histories, we want the parent versions
of the previous commits rather than the --no-merges.  The --no-merges
results in failures for the merges that include (vnl, hdf5, or other
Thirdparty updates).

2019-03-17 04:00 UTC, thewtex requested changes
Thanks, @hjmjohnson !

2019-03-17 04:00 UTC, thewtex commented on evaluate-itk-performance.py
> +        print("HERE!!!!")
Remove debug code

2019-03-17 15:05 UTC, hjmjohnson commented on evaluate-itk-performance.py
> +        print("HERE!!!!")
Done.  Thanks for reviewing.

2019-03-17 20:22 UTC, thewtex submitted a review, later dismissed

2019-03-17 20:22 UTC, thewtex commented on src/PerformanceBenchmarkingInformation.h.in
> +#cmakedefine ITK_USES_NUMEROFTHREADS
`NUMEROFTHREADS` -> `NUMBEROFTHREADS`

2019-03-18 12:58 UTC, hjmjohnson commented on src/PerformanceBenchmarkingInformation.h.in
> +#cmakedefine ITK_USES_NUMEROFTHREADS
Thanks.  Fixed.

2019-03-18 14:39 UTC, dzenanz approved these changes

2019-03-19 23:28 UTC, hjmjohnson commented on evaluate-itk-performance.py
>          default='--no-merges HEAD~1..')
Done. Thanks.

2019-03-20 20:55 UTC, thewtex commented
Any ideas why the build is failing?

2019-03-20 21:20 UTC, dzenanz commented
```text
Build project
   Each symbol represents 1024 bytes of output.
   '!' represents an error and '*' a warning.
    ...!...!.. Size of output: 10K
Error(s) when building project
   3 Compiler errors
   1 Compiler warnings
```
[Link](https://dev.azure.com/InsightSoftwareConsortium/ITKModules/_build/results?buildId=481&view=logs&jobId=ad07b744-5a1a-5d54-7693-fcb02e666633&taskId=f71dc17c-82b5-5f61-bb27-f647852fa814&lineStart=46&lineEnd=52&colStart=1&colEnd=23)

3 executables cannot be found, the others are not run:
```text
Unable to find executable: /home/vsts/work/1/ITKBenchmarks-build/Segmentation/WatershedBenchmark
Unable to find executable: /home/vsts/work/1/ITKBenchmarks-build/Segmentation/MorphologicalWatershedBenchmark
Unable to find executable: /home/vsts/work/1/ITKBenchmarks-build/Segmentation/LevelSetBenchmark
```

2026-04-13 21:30 UTC, thewtex approved these changes

2026-04-14 18:13 UTC, merged